# Use postgres/example user/password credentials
version: '3.1'

services:
  postgres_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: usuario
      POSTGRES_DB: parking-management-db
    ports:
      - 5432:5432
